import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const defaultFont = localFont({
    src: [
        {
            path: "../../public/fonts/Suisse Intl/SuisseIntl-Black.woff2",
            weight: "900",
            style: "normal",
        },
        {
            path: "../../public/fonts/Suisse Intl/SuisseIntl-Bold.woff2",
            weight: "700",
            style: "normal",
        },
        {
            path: "../../public/fonts/Suisse Intl/SuisseIntl-SemiBold.woff2",
            weight: "600",
            style: "normal",
        },
        {
            path: "../../public/fonts/Suisse Intl/SuisseIntl-Medium.woff2",
            weight: "500",
            style: "normal",
        },
        {
            path: "../../public/fonts/Suisse Intl/SuisseIntl-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/Suisse Intl/SuisseIntl-Thin.woff2",
            weight: "100",
            style: "normal",
        },
    ],
    display: "swap",
    variable: "--font-suisseintl",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={"font-default"}>
                {children}
            </body>
        </html>
    );
}
